spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 441113075662-d9pncbkkaa71ktggpv6n47d9jhfs6lge.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot